version: "3.8"

services:
  car_api_backend:
    container_name: car_api_backend
    image: node_app
    build: ./
    command: >
      bash -c "npm run start"
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - car_api_postgres
      - car_api_rabbitmq
    networks:
      - br0

  car_api_postgres:
    container_name: car_api_postgres
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - br0

  car_api_rabbitmq:
    container_name: car_api_rabbit
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - br0

networks:
  br0:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
